/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package code.programmain;

import java.util.Random;

/**
 *
 * @author bruno
 */
public class JogoAdivinha extends javax.swing.JFrame {

    /**
     * Creates new form JogoAdivinha
     */
    public JogoAdivinha() {
        initComponents();
        //Criando frase e quebrando linhas com html
        lblFrase.setText("<html>Estou pensando em um número, entre 0 e 5. Tente adivinhar!</html>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        boxVal = new javax.swing.JSpinner();
        btnAcao = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblFrase = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Adivinhe o Valor");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        boxVal.setModel(new javax.swing.SpinnerNumberModel(0, 0, 5, 1));
        getContentPane().add(boxVal, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 256, 75, 30));

        btnAcao.setBackground(new java.awt.Color(153, 0, 255));
        btnAcao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAcao.setForeground(new java.awt.Color(255, 255, 255));
        btnAcao.setText("Tente a sorte!");
        btnAcao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcaoActionPerformed(evt);
            }
        });
        getContentPane().add(btnAcao, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 304, 125, 35));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/genioImage.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 6, -1, -1));

        lblFrase.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblFrase.setForeground(new java.awt.Color(0, 0, 0));
        lblFrase.setText("Frase");
        lblFrase.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(lblFrase, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 200, 90));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/falaDesen.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Ação do botão
    private void btnAcaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcaoActionPerformed
        // Pegando valor
        int val = Integer.parseInt(boxVal.getValue().toString());   //Converter
        Random random = new Random();   //Biblioteca para randomizar
        int valRand = (int) random.nextInt(6);    //6 para pegar o 5, último valor desconsidera
        //System.out.println(valRand);    //Debug
        if(val == valRand){ //básico de condição apenas conferindo se um é igual a outro
            lblFrase.setText("<html>PARABENS! Você acertou o valor, o valor foi "+Integer.toString(valRand)+"</html>");
        }else{
            lblFrase.setText("<html>ERROU! Tente novamente, o valor correto era "+Integer.toString(valRand)+"</html>");
        }
    }//GEN-LAST:event_btnAcaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JogoAdivinha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JogoAdivinha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JogoAdivinha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JogoAdivinha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JogoAdivinha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner boxVal;
    private javax.swing.JButton btnAcao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblFrase;
    // End of variables declaration//GEN-END:variables
}
